import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from './(componant)/Navbar/Navbar.jsx';
import Footer from './(componant)/Footer/Footer.jsx';
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import { Toaster } from "react-hot-toast";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "My Website",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} min-h-[100vh] flex flex-col overflow-x-hidden`}>
        <Navbar />
        <div className="container md:px-40 my-5">
          {children}
        </div>
        <Footer />
        <Toaster />
      </body>
    </html>
  );
}
